package de.platen.cass.guiserver.frontend.guielement;

public enum View {
	ACTIVE, INACTIVE, MOUSEOVER, PRESSED, DRAGGED, INACTIVE_MOUSEOVER, ACTIVE_DESELECTED, ACTIVE_SELECTED,
	ACTIVE_DESELECTED_MOUSEOVER, ACTIVE_SELECTED_MOUSEOVER, INACTIVE_DESELECTED, INACTIVE_SELECTED, FOCUS,
	MOUSE_OVER_ACTIVE, MOUSE_OVER_FOCUS
}
